#!/bin/bash

source .env

export COGNITO_PROVIDER_GOOGLE_CLIENT_ID=${COGNITO_PROVIDER_GOOGLE_CLIENT_ID}
export COGNITO_PROVIDER_GOOGLE_CLIENT_SECRET=${COGNITO_PROVIDER_GOOGLE_CLIENT_SECRET}

cdk destroy --all
